# 1. Write a python program to add two numbers. 
a = (int(input("Enter a : ")))
b = (int(input("Enter b : ")))
print("The sum of", a, "and", b, "is", a+b)
print(f"The sum of {a} and {b} is {a+b}")





#  2. Write a python program to find remainder when a number is divided by z.
z = int(input("Enter z : "))
c = int(input("Enter c : "))
print("When", c, "is divided by", z, "than the remainder is", z%c)





# 4. Use comparison operator to find out whether ‘x’ and 'y' given
# variable 'y' is greater than ‘x’ or not. Take x = 34 and y = 80.
x = 34
y = 80
print(y>x) 
# If output = True (yes y is greater than x)
# If output = False (No y is not greater than x)





# 5. Write a python program to find an average of two numbers entered by the user.
m = int(input("Enter m : "))
n = int(input("Enter n : "))
print("The average value of", m, "and", n, "is", (m+n)/2)





# 6. Write a python program to calculate the square of a number entered by the user.
s = int(input("Enter s : "))
print("The square of", s, "is", s * s)