print(f" 0 | 1 | 2 ")         
print(f"___|___|___")
print(f" 3 | 4 | 5 ")
print(f"___|___|___")
print(f" 6 | 7 | 8 ")
print("\n")


print("Now, X turn")
X = int(input("Enter position of X 0-8 : "))

print("Now, O turn")
O = int(input("Enter position of 0-8 : "))



if(X==0):
    a = "X"
else:
    a = "0"

# a = if(X==0): print("X") else: print("0")



    print(f" a | 1 | 2 ")         
    print(f"___|___|___")
    print(f" 3 | 4 | 5 ")
    print(f"___|___|___")
    print(f" 6 | 7 | 8 ")
    print("\n")




# zero = if(X=0): print("X") else: print("0")


# print(f" a | 1 | 2 ")
# print(f"___|___|___")
# print(f" 3 | 4 | 5 ")
# print(f"___|___|___")
# print(f" 6 | 7 | 8 ")
# print("\n")

